name: moviesapproute
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.1
  shared_preferences: ^2.5.3
  dots_indicator: ^4.0.1
  introduction_screen: ^4.0.0
  http: ^1.5.0
  get: ^4.7.2
  dio: ^5.4.0
  get_it: ^8.2.0
  dart_either: ^2.0.0
  api_exception: ^0.0.3
  flutter_bloc: ^9.1.1
  lucide_icons: ^0.257.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

dependency_overrides:
  http: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
